console.log('Hello World !')
let  teste = ('testando')
console.log(teste)
let pprt = ('ai rafinha,amanha tem aula as 15 em,te espero sem 1 minuto de atraso')
console.log(pprt)
let commit = ('perae so mais um commit pra ficar bonitinho la')
console.log(commit)