console.log('Hello World !')
let  teste = ('testando')
console.log(teste)
let pprt = ('ai rafinha,amanha tem aula as 15 em,te espero sem 1 minuto de atraso')
console.log(pprt)
let commit = ('perae so mais um commit pra ficar bonitinho la')
console.log(commit)
let hahaha = ('achou q n ia ter o quarto commit ne HAHAHAHAHAHA')
console.log(hahaha)
let sald = (teste + pprt)
console.log(sald)
console.log(teste + pprt)